# Generated by Django 2.2.1 on 2019-05-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_professor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
